services:
  nginx:
    build:
      context: ./nginx/
    container_name: nginx
    ports:
      - "443:443"
    restart: unless-stopped
    depends_on:
      - mariadb
  mariadb:
    build:
      context: ./mariaDB/
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mariadb_data:
