services:
  nginx:
    build:
      context: ./nginx/
    container_name: nginx
    ports:
      - "443:443"
  mariadb:
    build: context:./mariaDB/
    container_name: mariadb
    ports:
      - "3306:3306"
