services:
  nginx:
    build:
      context: ./nginx/
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
  mariadb:
    build:
      context: ./mariaDB/
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - inception_network
  wordpress:
    build:
      context: ./wordpress/
    container_name: wordpress
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_PORT=3306

    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
      - nginx
    restart: unless-stopped
    networks:
      - inception_network

volumes:
  mariadb_data:
  wordpress_data:

networks:
  inception_network:
    driver: bridge
